# coding: utf-8

"""
    overbae API

    Backend API for the overclaw agent optimization platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overclaw.openapi_client.models.span_type_enum import SpanTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class Span(BaseModel):
    """
    Span
    """ # noqa: E501
    id: UUID
    trace: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    span_type: SpanTypeEnum
    name: Annotated[str, Field(strict=True, max_length=255)]
    order: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)]] = None
    start_time: Optional[Union[StrictFloat, StrictInt]] = None
    end_time: Optional[Union[StrictFloat, StrictInt]] = None
    latency_ms: Optional[Union[StrictFloat, StrictInt]] = None
    metadata: Optional[Any] = None
    error: Optional[StrictStr] = None
    user: StrictInt
    __properties: ClassVar[List[str]] = ["id", "trace", "span_type", "name", "order", "start_time", "end_time", "latency_ms", "metadata", "error", "user"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Span from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "user",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if trace (nullable) is None
        # and model_fields_set contains the field
        if self.trace is None and "trace" in self.model_fields_set:
            _dict['trace'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Span from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "trace": obj.get("trace"),
            "span_type": obj.get("span_type"),
            "name": obj.get("name"),
            "order": obj.get("order"),
            "start_time": obj.get("start_time"),
            "end_time": obj.get("end_time"),
            "latency_ms": obj.get("latency_ms"),
            "metadata": obj.get("metadata"),
            "error": obj.get("error"),
            "user": obj.get("user")
        })
        return _obj


