# coding: utf-8

"""
    overbae API

    Backend API for the overclaw agent optimization platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Status1b7Enum(str, Enum):
    """
    * `pending` - Pending * `running` - Running * `completed` - Completed * `failed` - Failed * `cancelled` - Cancelled
    """

    """
    allowed enum values
    """
    PENDING = 'pending'
    RUNNING = 'running'
    COMPLETED = 'completed'
    FAILED = 'failed'
    CANCELLED = 'cancelled'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Status1b7Enum from a JSON string"""
        return cls(json.loads(json_str))


