# coding: utf-8

"""
    overbae API

    Backend API for the overclaw agent optimization platform.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overclaw.openapi_client.models.suggestion_status_enum import SuggestionStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class Suggestion(BaseModel):
    """
    Suggestion
    """ # noqa: E501
    id: UUID
    status: Optional[SuggestionStatusEnum] = None
    title: Annotated[str, Field(strict=True, max_length=512)]
    description: Optional[StrictStr] = None
    change_type: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    score_before: Optional[Union[StrictFloat, StrictInt]] = None
    score_after: Optional[Union[StrictFloat, StrictInt]] = None
    created_at: datetime
    updated_at: datetime
    user: StrictInt
    agent: UUID
    job: Optional[UUID] = None
    iteration: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["id", "status", "title", "description", "change_type", "score_before", "score_after", "created_at", "updated_at", "user", "agent", "job", "iteration"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Suggestion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "created_at",
            "updated_at",
            "user",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if score_before (nullable) is None
        # and model_fields_set contains the field
        if self.score_before is None and "score_before" in self.model_fields_set:
            _dict['score_before'] = None

        # set to None if score_after (nullable) is None
        # and model_fields_set contains the field
        if self.score_after is None and "score_after" in self.model_fields_set:
            _dict['score_after'] = None

        # set to None if job (nullable) is None
        # and model_fields_set contains the field
        if self.job is None and "job" in self.model_fields_set:
            _dict['job'] = None

        # set to None if iteration (nullable) is None
        # and model_fields_set contains the field
        if self.iteration is None and "iteration" in self.model_fields_set:
            _dict['iteration'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Suggestion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "status": obj.get("status"),
            "title": obj.get("title"),
            "description": obj.get("description"),
            "change_type": obj.get("change_type"),
            "score_before": obj.get("score_before"),
            "score_after": obj.get("score_after"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "user": obj.get("user"),
            "agent": obj.get("agent"),
            "job": obj.get("job"),
            "iteration": obj.get("iteration")
        })
        return _obj


