"""Mutable in-memory view of the artifacts preflight is allowed to touch.

The autofix handlers mutate ``state.eval_spec`` / ``state.dataset`` in
memory and append :class:`PatchRecord` entries.  The runner then writes
the updated dicts back to disk and snapshots the previous version for
audit.

Keeping IO at the boundary lets every handler stay pure and trivially
testable.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from overmind.core.paths import (
    agent_instrumented_dir,
    agent_setup_spec_dir,
)
from overmind.core.registry import resolve_agent


def _sha256(data: bytes | str) -> str:
    if isinstance(data, str):
        data = data.encode()
    return hashlib.sha256(data).hexdigest()


@dataclass
class WorkingState:
    """In-memory bundle of everything the autofix handlers may mutate."""

    agent_name: str
    eval_spec: dict[str, Any]
    dataset: list[dict]
    eval_spec_path: Path
    dataset_path: Path
    instrumented_dir: Path
    # Per-iteration set of relative paths (relative to ``instrumented_dir``)
    # that handlers asked the runner to re-instrument.  The runner
    # consumes and clears it between iterations.
    reinstrument_requests: set[str] = field(default_factory=set)
    # Per-iteration set of dependency package names that handlers want
    # added to the instrumented copy's requirements.txt.
    deps_to_add: set[str] = field(default_factory=set)
    # Absolute path to the registered Overmind entrypoint *harness* file
    # (the thin file generated by /overmind-register-agent — NOT the native
    # agent code it imports).  Preflight is allowed to repair this file;
    # everything else under the agent source tree is off-limits.
    entrypoint_path: Path | None = None
    # How many entrypoint LLM-repair attempts have been made this run.
    # Capped to keep cost bounded.
    entrypoint_repair_attempts: int = 0
    max_entrypoint_repairs: int = 2

    @classmethod
    def load(cls, agent_name: str) -> WorkingState:
        spec_path = agent_setup_spec_dir(agent_name) / "eval_spec.json"
        ds_path = agent_setup_spec_dir(agent_name) / "dataset.json"
        if not spec_path.is_file():
            raise FileNotFoundError(f"eval_spec.json not found: {spec_path}")
        if not ds_path.is_file():
            raise FileNotFoundError(f"dataset.json not found: {ds_path}")
        eval_spec = json.loads(spec_path.read_text())
        raw_ds = json.loads(ds_path.read_text())
        if isinstance(raw_ds, dict) and "test_cases" in raw_ds:
            dataset = list(raw_ds["test_cases"])
        elif isinstance(raw_ds, list):
            dataset = list(raw_ds)
        else:
            dataset = []
        try:
            file_path, _fn_name = resolve_agent(agent_name)
            entrypoint_path: Path | None = Path(file_path) if file_path else None
        except SystemExit:
            entrypoint_path = None
        except Exception:
            entrypoint_path = None
        return cls(
            agent_name=agent_name,
            eval_spec=eval_spec,
            dataset=dataset,
            eval_spec_path=spec_path,
            dataset_path=ds_path,
            instrumented_dir=agent_instrumented_dir(agent_name),
            entrypoint_path=entrypoint_path,
        )

    # ------------------------------------------------------------------
    # Snapshots / persistence
    # ------------------------------------------------------------------

    def file_hash(self, path: Path) -> str:
        if not path.is_file():
            return ""
        return _sha256(path.read_bytes())

    def snapshot_into(self, target_dir: Path) -> None:
        """Copy the artifacts the handlers might mutate into *target_dir*."""
        target_dir.mkdir(parents=True, exist_ok=True)
        if self.eval_spec_path.is_file():
            (target_dir / "eval_spec.json").write_bytes(self.eval_spec_path.read_bytes())
        if self.dataset_path.is_file():
            (target_dir / "dataset.json").write_bytes(self.dataset_path.read_bytes())
        if self.entrypoint_path and self.entrypoint_path.is_file():
            ep_dir = target_dir / "entrypoint"
            ep_dir.mkdir(parents=True, exist_ok=True)
            (ep_dir / self.entrypoint_path.name).write_bytes(self.entrypoint_path.read_bytes())

    def persist(self) -> tuple[bool, bool]:
        """Write any in-memory changes back to disk.

        Returns ``(eval_spec_changed, dataset_changed)`` for the runner's
        log line.
        """
        new_spec = json.dumps(self.eval_spec, indent=2, sort_keys=False) + "\n"
        new_ds = json.dumps(self.dataset, indent=2, default=str) + "\n"

        spec_changed = False
        ds_changed = False

        old_spec = self.eval_spec_path.read_text() if self.eval_spec_path.is_file() else ""
        if old_spec != new_spec:
            self.eval_spec_path.write_text(new_spec)
            spec_changed = True

        old_ds = self.dataset_path.read_text() if self.dataset_path.is_file() else ""
        if old_ds != new_ds:
            self.dataset_path.write_text(new_ds)
            ds_changed = True

        return spec_changed, ds_changed
