# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AliasPrStatusEnum(str, Enum):
    """
    * `not_started` - Not started * `in_progress` - In progress * `pr_open` - PR open * `merged` - Merged * `error` - Error
    """

    """
    allowed enum values
    """
    NOT_STARTED = 'not_started'
    IN_PROGRESS = 'in_progress'
    PR_OPEN = 'pr_open'
    MERGED = 'merged'
    ERROR = 'error'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AliasPrStatusEnum from a JSON string"""
        return cls(json.loads(json_str))


