# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.evaluator_kind_enum import EvaluatorKindEnum
from overmind.openapi_client.models.evaluator_scope_enum import EvaluatorScopeEnum
from overmind.openapi_client.models.score_data_type_enum import ScoreDataTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class BehaviourEvaluator(BaseModel):
    """
    BehaviourEvaluator
    """ # noqa: E501
    id: UUID
    name: Annotated[str, Field(strict=True, max_length=255)]
    display_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    description: Optional[StrictStr] = None
    kind: EvaluatorKindEnum
    scope: Optional[EvaluatorScopeEnum] = None
    score_type: Optional[ScoreDataTypeEnum] = None
    behaviour_binding: Dict[str, Any]
    __properties: ClassVar[List[str]] = ["id", "name", "display_name", "description", "kind", "scope", "score_type", "behaviour_binding"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BehaviourEvaluator from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "behaviour_binding",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BehaviourEvaluator from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "display_name": obj.get("display_name"),
            "description": obj.get("description"),
            "kind": obj.get("kind"),
            "scope": obj.get("scope"),
            "score_type": obj.get("score_type"),
            "behaviour_binding": obj.get("behaviour_binding")
        })
        return _obj


