# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from overmind.openapi_client.models.behaviour_authoring_step import BehaviourAuthoringStep
from overmind.openapi_client.models.behaviour_tool import BehaviourTool
from typing import Optional, Set
from typing_extensions import Self

class BehaviourAuthoringContract(BaseModel):
    """
    BehaviourAuthoringContract
    """ # noqa: E501
    anchor_sequence: List[StrictStr]
    steps: List[BehaviourAuthoringStep]
    tool_set: List[BehaviourTool]
    terminal: Optional[Any]
    __properties: ClassVar[List[str]] = ["anchor_sequence", "steps", "tool_set", "terminal"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BehaviourAuthoringContract from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in steps (list)
        _items = []
        if self.steps:
            for _item_steps in self.steps:
                if _item_steps:
                    _items.append(_item_steps.to_dict())
            _dict['steps'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in tool_set (list)
        _items = []
        if self.tool_set:
            for _item_tool_set in self.tool_set:
                if _item_tool_set:
                    _items.append(_item_tool_set.to_dict())
            _dict['tool_set'] = _items
        # set to None if terminal (nullable) is None
        # and model_fields_set contains the field
        if self.terminal is None and "terminal" in self.model_fields_set:
            _dict['terminal'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BehaviourAuthoringContract from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "anchor_sequence": obj.get("anchor_sequence"),
            "steps": [BehaviourAuthoringStep.from_dict(_item) for _item in obj["steps"]] if obj.get("steps") is not None else None,
            "tool_set": [BehaviourTool.from_dict(_item) for _item in obj["tool_set"]] if obj.get("tool_set") is not None else None,
            "terminal": obj.get("terminal")
        })
        return _obj


