# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.capability_status_enum import CapabilityStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class CapabilityList(BaseModel):
    """
    CapabilityList
    """ # noqa: E501
    id: UUID
    project: UUID
    name: Annotated[str, Field(strict=True, max_length=255)]
    slug: Annotated[str, Field(strict=True, max_length=255)]
    description: Optional[StrictStr] = None
    source_path: Optional[Annotated[str, Field(strict=True, max_length=512)]] = None
    model: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    active_model: Optional[UUID] = None
    structure_weight: Optional[Union[StrictFloat, StrictInt]] = None
    total_points: Optional[Union[StrictFloat, StrictInt]] = None
    tool_usage_weight: Optional[Union[StrictFloat, StrictInt]] = None
    status: Optional[CapabilityStatusEnum] = None
    observed: Optional[StrictBool] = None
    suggested_name: StrictStr
    entrypoint_fn: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    analyzer_model: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    dataset_size: StrictInt
    dataset_has_expected_output: Optional[StrictBool] = None
    dataset_input_keys: List[StrictStr] = Field(description="Card / ``input_schema`` wins over capture ``dataset_input_keys``.")
    tool_names: List[StrictStr] = Field(description="Card ``tool_spec`` wins over capture ``tool_config``.")
    cli_version: Optional[Annotated[str, Field(strict=True, max_length=20)]] = None
    modality: StrictStr = Field(description="Capability-card modality (text/code/tabular/multimodal…), \"\" when unanalyzed.")
    last_activity_at: Optional[datetime] = None
    trace_count: Optional[StrictInt] = Field(description="Distinct-trace count annotated by CapabilityViewSet; null elsewhere.")
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "project", "name", "slug", "description", "source_path", "model", "active_model", "structure_weight", "total_points", "tool_usage_weight", "status", "observed", "suggested_name", "entrypoint_fn", "analyzer_model", "dataset_size", "dataset_has_expected_output", "dataset_input_keys", "tool_names", "cli_version", "modality", "last_activity_at", "trace_count", "created_at", "updated_at"]

    @field_validator('slug')
    def slug_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[-a-zA-Z0-9_]+$", value):
            raise ValueError(r"must validate the regular expression /^[-a-zA-Z0-9_]+$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CapabilityList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "suggested_name",
            "dataset_size",
            "dataset_input_keys",
            "tool_names",
            "modality",
            "trace_count",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if active_model (nullable) is None
        # and model_fields_set contains the field
        if self.active_model is None and "active_model" in self.model_fields_set:
            _dict['active_model'] = None

        # set to None if last_activity_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_activity_at is None and "last_activity_at" in self.model_fields_set:
            _dict['last_activity_at'] = None

        # set to None if trace_count (nullable) is None
        # and model_fields_set contains the field
        if self.trace_count is None and "trace_count" in self.model_fields_set:
            _dict['trace_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CapabilityList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project": obj.get("project"),
            "name": obj.get("name"),
            "slug": obj.get("slug"),
            "description": obj.get("description"),
            "source_path": obj.get("source_path"),
            "model": obj.get("model"),
            "active_model": obj.get("active_model"),
            "structure_weight": obj.get("structure_weight"),
            "total_points": obj.get("total_points"),
            "tool_usage_weight": obj.get("tool_usage_weight"),
            "status": obj.get("status"),
            "observed": obj.get("observed"),
            "suggested_name": obj.get("suggested_name"),
            "entrypoint_fn": obj.get("entrypoint_fn"),
            "analyzer_model": obj.get("analyzer_model"),
            "dataset_size": obj.get("dataset_size"),
            "dataset_has_expected_output": obj.get("dataset_has_expected_output"),
            "dataset_input_keys": obj.get("dataset_input_keys"),
            "tool_names": obj.get("tool_names"),
            "cli_version": obj.get("cli_version"),
            "modality": obj.get("modality"),
            "last_activity_at": obj.get("last_activity_at"),
            "trace_count": obj.get("trace_count"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


