# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.chat_message_role_enum import ChatMessageRoleEnum
from overmind.openapi_client.models.turn_status_enum import TurnStatusEnum
from typing import Optional, Set
from typing_extensions import Self

class ChatMessage(BaseModel):
    """
    ChatMessage
    """ # noqa: E501
    id: UUID
    session: UUID
    role: ChatMessageRoleEnum
    content: StrictStr
    action_type: Optional[Annotated[str, Field(strict=True, max_length=64)]] = None
    action_data: Optional[Any] = None
    parts: Optional[Any] = None
    token_count: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    turn_status: Optional[TurnStatusEnum] = None
    created_at: datetime
    __properties: ClassVar[List[str]] = ["id", "session", "role", "content", "action_type", "action_data", "parts", "token_count", "turn_status", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChatMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "session",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if action_data (nullable) is None
        # and model_fields_set contains the field
        if self.action_data is None and "action_data" in self.model_fields_set:
            _dict['action_data'] = None

        # set to None if parts (nullable) is None
        # and model_fields_set contains the field
        if self.parts is None and "parts" in self.model_fields_set:
            _dict['parts'] = None

        # set to None if token_count (nullable) is None
        # and model_fields_set contains the field
        if self.token_count is None and "token_count" in self.model_fields_set:
            _dict['token_count'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChatMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "session": obj.get("session"),
            "role": obj.get("role"),
            "content": obj.get("content"),
            "action_type": obj.get("action_type"),
            "action_data": obj.get("action_data"),
            "parts": obj.get("parts"),
            "token_count": obj.get("token_count"),
            "turn_status": obj.get("turn_status"),
            "created_at": obj.get("created_at")
        })
        return _obj


