# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConnectorCapabilityMappingWriteSourceEnum(str, Enum):
    """
    * `observation_name` - observation_name * `metadata` - metadata * `tag` - tag * `trace_name` - trace_name
    """

    """
    allowed enum values
    """
    OBSERVATION_NAME = 'observation_name'
    METADATA = 'metadata'
    TAG = 'tag'
    TRACE_NAME = 'trace_name'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConnectorCapabilityMappingWriteSourceEnum from a JSON string"""
        return cls(json.loads(json_str))


