# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class ConnectorCapabilityMappingWriteRequest(BaseModel):
    """
    ConnectorCapabilityMappingWriteRequest
    """ # noqa: E501
    source: Optional[StrictStr] = None
    key: Optional[StrictStr] = None
    names: Optional[List[Annotated[str, Field(min_length=1, strict=True)]]] = None
    assignments: Optional[Dict[str, Annotated[str, Field(min_length=1, strict=True)]]] = None
    auto_create: Optional[StrictBool] = False
    fallback_capability_id: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["source", "key", "names", "assignments", "auto_create", "fallback_capability_id"]

    @field_validator('source')
    def source_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['observation_name', 'metadata', 'tag', 'trace_name', '']):
            raise ValueError("must be one of enum values ('observation_name', 'metadata', 'tag', 'trace_name', '')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ConnectorCapabilityMappingWriteRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if key (nullable) is None
        # and model_fields_set contains the field
        if self.key is None and "key" in self.model_fields_set:
            _dict['key'] = None

        # set to None if fallback_capability_id (nullable) is None
        # and model_fields_set contains the field
        if self.fallback_capability_id is None and "fallback_capability_id" in self.model_fields_set:
            _dict['fallback_capability_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ConnectorCapabilityMappingWriteRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "source": obj.get("source"),
            "key": obj.get("key"),
            "names": obj.get("names"),
            "assignments": obj.get("assignments"),
            "auto_create": obj.get("auto_create") if obj.get("auto_create") is not None else False,
            "fallback_capability_id": obj.get("fallback_capability_id")
        })
        return _obj


