# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from overmind.openapi_client.models.deployed_model_status_enum import DeployedModelStatusEnum
from overmind.openapi_client.models.quantization_enum import QuantizationEnum
from typing import Optional, Set
from typing_extensions import Self

class DeployedModel(BaseModel):
    """
    DeployedModel
    """ # noqa: E501
    id: UUID
    project: UUID
    model_id: StrictStr
    status: DeployedModelStatusEnum
    quantization: QuantizationEnum
    base_model_id: StrictStr = Field(description="Base model ID used for the fine-tuning job.")
    gpu_type: StrictStr = Field(description="Modal GPU type: 'L4' or 'L40S'.")
    is_lora: StrictBool
    lora_rank: StrictInt = Field(description="LoRA rank; 0 for full models.")
    weights_path: StrictStr = Field(description="Path inside the Modal overmind-weights Volume.")
    checkpoint_hash: StrictStr = Field(description="Content hash of the quantized weights directory.")
    max_model_len: StrictInt = Field(description="Maximum context length passed to vLLM --max-model-len.")
    num_parameters: StrictInt
    sla_tier: StrictStr = Field(description="'hot' keeps a warm container alive; 'standard' scales to zero.")
    inference_url: StrictStr = Field(description="Modal web endpoint URL for the model's vLLM container pool.")
    error_message: StrictStr
    created_at: datetime
    deployed_at: Optional[datetime]
    finetuning_job_id: UUID
    finetuning_job_name: Optional[StrictStr]
    capability_id: Optional[StrictStr]
    capability_name: Optional[StrictStr]
    request_count: StrictInt
    last_active_at: Optional[datetime]
    total_tokens: Optional[StrictInt]
    avg_tokens_per_second: Optional[Union[StrictFloat, StrictInt]]
    avg_latency_ms: Optional[Union[StrictFloat, StrictInt]]
    cost_total: Optional[Union[StrictFloat, StrictInt]]
    cost_this_month: Optional[Union[StrictFloat, StrictInt]]
    __properties: ClassVar[List[str]] = ["id", "project", "model_id", "status", "quantization", "base_model_id", "gpu_type", "is_lora", "lora_rank", "weights_path", "checkpoint_hash", "max_model_len", "num_parameters", "sla_tier", "inference_url", "error_message", "created_at", "deployed_at", "finetuning_job_id", "finetuning_job_name", "capability_id", "capability_name", "request_count", "last_active_at", "total_tokens", "avg_tokens_per_second", "avg_latency_ms", "cost_total", "cost_this_month"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeployedModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "project",
            "model_id",
            "status",
            "quantization",
            "base_model_id",
            "gpu_type",
            "is_lora",
            "lora_rank",
            "weights_path",
            "checkpoint_hash",
            "max_model_len",
            "num_parameters",
            "sla_tier",
            "inference_url",
            "error_message",
            "created_at",
            "deployed_at",
            "finetuning_job_id",
            "finetuning_job_name",
            "capability_id",
            "capability_name",
            "request_count",
            "last_active_at",
            "total_tokens",
            "avg_tokens_per_second",
            "avg_latency_ms",
            "cost_total",
            "cost_this_month",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if deployed_at (nullable) is None
        # and model_fields_set contains the field
        if self.deployed_at is None and "deployed_at" in self.model_fields_set:
            _dict['deployed_at'] = None

        # set to None if finetuning_job_name (nullable) is None
        # and model_fields_set contains the field
        if self.finetuning_job_name is None and "finetuning_job_name" in self.model_fields_set:
            _dict['finetuning_job_name'] = None

        # set to None if capability_id (nullable) is None
        # and model_fields_set contains the field
        if self.capability_id is None and "capability_id" in self.model_fields_set:
            _dict['capability_id'] = None

        # set to None if capability_name (nullable) is None
        # and model_fields_set contains the field
        if self.capability_name is None and "capability_name" in self.model_fields_set:
            _dict['capability_name'] = None

        # set to None if last_active_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_active_at is None and "last_active_at" in self.model_fields_set:
            _dict['last_active_at'] = None

        # set to None if total_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.total_tokens is None and "total_tokens" in self.model_fields_set:
            _dict['total_tokens'] = None

        # set to None if avg_tokens_per_second (nullable) is None
        # and model_fields_set contains the field
        if self.avg_tokens_per_second is None and "avg_tokens_per_second" in self.model_fields_set:
            _dict['avg_tokens_per_second'] = None

        # set to None if avg_latency_ms (nullable) is None
        # and model_fields_set contains the field
        if self.avg_latency_ms is None and "avg_latency_ms" in self.model_fields_set:
            _dict['avg_latency_ms'] = None

        # set to None if cost_total (nullable) is None
        # and model_fields_set contains the field
        if self.cost_total is None and "cost_total" in self.model_fields_set:
            _dict['cost_total'] = None

        # set to None if cost_this_month (nullable) is None
        # and model_fields_set contains the field
        if self.cost_this_month is None and "cost_this_month" in self.model_fields_set:
            _dict['cost_this_month'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeployedModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project": obj.get("project"),
            "model_id": obj.get("model_id"),
            "status": obj.get("status"),
            "quantization": obj.get("quantization"),
            "base_model_id": obj.get("base_model_id"),
            "gpu_type": obj.get("gpu_type"),
            "is_lora": obj.get("is_lora"),
            "lora_rank": obj.get("lora_rank"),
            "weights_path": obj.get("weights_path"),
            "checkpoint_hash": obj.get("checkpoint_hash"),
            "max_model_len": obj.get("max_model_len"),
            "num_parameters": obj.get("num_parameters"),
            "sla_tier": obj.get("sla_tier"),
            "inference_url": obj.get("inference_url"),
            "error_message": obj.get("error_message"),
            "created_at": obj.get("created_at"),
            "deployed_at": obj.get("deployed_at"),
            "finetuning_job_id": obj.get("finetuning_job_id"),
            "finetuning_job_name": obj.get("finetuning_job_name"),
            "capability_id": obj.get("capability_id"),
            "capability_name": obj.get("capability_name"),
            "request_count": obj.get("request_count") if obj.get("request_count") is not None else 0,
            "last_active_at": obj.get("last_active_at"),
            "total_tokens": obj.get("total_tokens"),
            "avg_tokens_per_second": obj.get("avg_tokens_per_second"),
            "avg_latency_ms": obj.get("avg_latency_ms"),
            "cost_total": obj.get("cost_total"),
            "cost_this_month": obj.get("cost_this_month")
        })
        return _obj


