# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DivergenceStateEnum(str, Enum):
    """
    * `in_sync` - In sync * `diverged` - Diverged * `branch_missing` - Branch missing * `repo_missing` - Repository missing
    """

    """
    allowed enum values
    """
    IN_SYNC = 'in_sync'
    DIVERGED = 'diverged'
    BRANCH_MISSING = 'branch_missing'
    REPO_MISSING = 'repo_missing'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DivergenceStateEnum from a JSON string"""
        return cls(json.loads(json_str))


