# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class EvaluatorKindEnum(str, Enum):
    """
    * `llm_judge` - Llm Judge * `trajectory` - Trajectory * `deterministic` - Deterministic * `statistical` - Statistical * `agentic` - Agentic
    """

    """
    allowed enum values
    """
    LLM_JUDGE = 'llm_judge'
    TRAJECTORY = 'trajectory'
    DETERMINISTIC = 'deterministic'
    STATISTICAL = 'statistical'
    AGENTIC = 'agentic'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of EvaluatorKindEnum from a JSON string"""
        return cls(json.loads(json_str))


