# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from overmind.openapi_client.models.finetuning_benchmark_snapshot import FinetuningBenchmarkSnapshot
from overmind.openapi_client.models.finetuning_excluded_model import FinetuningExcludedModel
from overmind.openapi_client.models.finetuning_experiment import FinetuningExperiment
from overmind.openapi_client.models.finetuning_recommendation_dataset import FinetuningRecommendationDataset
from overmind.openapi_client.models.task_type_source_enum import TaskTypeSourceEnum
from typing import Optional, Set
from typing_extensions import Self

class FinetuningRecommendationResponse(BaseModel):
    """
    FinetuningRecommendationResponse
    """ # noqa: E501
    task_type: StrictStr
    task_type_source: TaskTypeSourceEnum
    skill_weights: Dict[str, Union[StrictFloat, StrictInt]]
    dataset: FinetuningRecommendationDataset
    candidates: List[FinetuningExperiment]
    excluded: List[FinetuningExcludedModel]
    shown: List[StrictStr]
    benchmark_snapshot: FinetuningBenchmarkSnapshot
    __properties: ClassVar[List[str]] = ["task_type", "task_type_source", "skill_weights", "dataset", "candidates", "excluded", "shown", "benchmark_snapshot"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FinetuningRecommendationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of dataset
        if self.dataset:
            _dict['dataset'] = self.dataset.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in candidates (list)
        _items = []
        if self.candidates:
            for _item_candidates in self.candidates:
                if _item_candidates:
                    _items.append(_item_candidates.to_dict())
            _dict['candidates'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in excluded (list)
        _items = []
        if self.excluded:
            for _item_excluded in self.excluded:
                if _item_excluded:
                    _items.append(_item_excluded.to_dict())
            _dict['excluded'] = _items
        # override the default output from pydantic by calling `to_dict()` of benchmark_snapshot
        if self.benchmark_snapshot:
            _dict['benchmark_snapshot'] = self.benchmark_snapshot.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FinetuningRecommendationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "task_type": obj.get("task_type"),
            "task_type_source": obj.get("task_type_source"),
            "skill_weights": obj.get("skill_weights"),
            "dataset": FinetuningRecommendationDataset.from_dict(obj["dataset"]) if obj.get("dataset") is not None else None,
            "candidates": [FinetuningExperiment.from_dict(_item) for _item in obj["candidates"]] if obj.get("candidates") is not None else None,
            "excluded": [FinetuningExcludedModel.from_dict(_item) for _item in obj["excluded"]] if obj.get("excluded") is not None else None,
            "shown": obj.get("shown"),
            "benchmark_snapshot": FinetuningBenchmarkSnapshot.from_dict(obj["benchmark_snapshot"]) if obj.get("benchmark_snapshot") is not None else None
        })
        return _obj


