# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.finetuning_job_status_enum import FinetuningJobStatusEnum
from overmind.openapi_client.models.model_tier_enum import ModelTierEnum
from overmind.openapi_client.models.provider_f46_enum import ProviderF46Enum
from overmind.openapi_client.models.split_method_enum import SplitMethodEnum
from typing import Optional, Set
from typing_extensions import Self

class FinetuningJobList(BaseModel):
    """
    FinetuningJobList
    """ # noqa: E501
    id: UUID
    project: UUID
    capability: Optional[UUID]
    dataset: UUID
    eval_dataset: Optional[UUID]
    eval_set: Optional[UUID]
    validation_enabled: StrictBool
    validation_split_ratio: Union[StrictFloat, StrictInt]
    validation_dataset: Optional[UUID]
    split_method: SplitMethodEnum
    name: StrictStr
    use_case: StrictStr
    base_model: StrictStr
    status: FinetuningJobStatusEnum
    group_id: Optional[UUID]
    model_tier: ModelTierEnum
    provider: ProviderF46Enum
    output_model_name: StrictStr
    deployed_model_id: Optional[UUID]
    model_weights_location: StrictStr
    progress: Optional[Any]
    model_pr: Optional[Dict[str, Any]]
    retry_count: StrictInt
    max_retries: StrictInt
    error_message: StrictStr
    cost_usd: Optional[Annotated[str, Field(strict=True)]]
    billed_minutes: Optional[StrictInt]
    cost_synced_at: Optional[datetime]
    created_at: datetime
    updated_at: datetime
    started_at: Optional[datetime]
    completed_at: Optional[datetime]
    __properties: ClassVar[List[str]] = ["id", "project", "capability", "dataset", "eval_dataset", "eval_set", "validation_enabled", "validation_split_ratio", "validation_dataset", "split_method", "name", "use_case", "base_model", "status", "group_id", "model_tier", "provider", "output_model_name", "deployed_model_id", "model_weights_location", "progress", "model_pr", "retry_count", "max_retries", "error_message", "cost_usd", "billed_minutes", "cost_synced_at", "created_at", "updated_at", "started_at", "completed_at"]

    @field_validator('cost_usd')
    def cost_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if not re.match(r"^-?\d{0,8}(?:\.\d{0,4})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,8}(?:\.\d{0,4})?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FinetuningJobList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "project",
            "capability",
            "dataset",
            "eval_dataset",
            "eval_set",
            "validation_enabled",
            "validation_split_ratio",
            "validation_dataset",
            "split_method",
            "name",
            "use_case",
            "base_model",
            "status",
            "group_id",
            "model_tier",
            "provider",
            "output_model_name",
            "deployed_model_id",
            "model_weights_location",
            "progress",
            "model_pr",
            "retry_count",
            "max_retries",
            "error_message",
            "cost_usd",
            "billed_minutes",
            "cost_synced_at",
            "created_at",
            "updated_at",
            "started_at",
            "completed_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if capability (nullable) is None
        # and model_fields_set contains the field
        if self.capability is None and "capability" in self.model_fields_set:
            _dict['capability'] = None

        # set to None if eval_dataset (nullable) is None
        # and model_fields_set contains the field
        if self.eval_dataset is None and "eval_dataset" in self.model_fields_set:
            _dict['eval_dataset'] = None

        # set to None if eval_set (nullable) is None
        # and model_fields_set contains the field
        if self.eval_set is None and "eval_set" in self.model_fields_set:
            _dict['eval_set'] = None

        # set to None if validation_dataset (nullable) is None
        # and model_fields_set contains the field
        if self.validation_dataset is None and "validation_dataset" in self.model_fields_set:
            _dict['validation_dataset'] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict['group_id'] = None

        # set to None if deployed_model_id (nullable) is None
        # and model_fields_set contains the field
        if self.deployed_model_id is None and "deployed_model_id" in self.model_fields_set:
            _dict['deployed_model_id'] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict['progress'] = None

        # set to None if model_pr (nullable) is None
        # and model_fields_set contains the field
        if self.model_pr is None and "model_pr" in self.model_fields_set:
            _dict['model_pr'] = None

        # set to None if cost_usd (nullable) is None
        # and model_fields_set contains the field
        if self.cost_usd is None and "cost_usd" in self.model_fields_set:
            _dict['cost_usd'] = None

        # set to None if billed_minutes (nullable) is None
        # and model_fields_set contains the field
        if self.billed_minutes is None and "billed_minutes" in self.model_fields_set:
            _dict['billed_minutes'] = None

        # set to None if cost_synced_at (nullable) is None
        # and model_fields_set contains the field
        if self.cost_synced_at is None and "cost_synced_at" in self.model_fields_set:
            _dict['cost_synced_at'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FinetuningJobList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project": obj.get("project"),
            "capability": obj.get("capability"),
            "dataset": obj.get("dataset"),
            "eval_dataset": obj.get("eval_dataset"),
            "eval_set": obj.get("eval_set"),
            "validation_enabled": obj.get("validation_enabled"),
            "validation_split_ratio": obj.get("validation_split_ratio"),
            "validation_dataset": obj.get("validation_dataset"),
            "split_method": obj.get("split_method"),
            "name": obj.get("name"),
            "use_case": obj.get("use_case"),
            "base_model": obj.get("base_model"),
            "status": obj.get("status"),
            "group_id": obj.get("group_id"),
            "model_tier": obj.get("model_tier"),
            "provider": obj.get("provider"),
            "output_model_name": obj.get("output_model_name"),
            "deployed_model_id": obj.get("deployed_model_id"),
            "model_weights_location": obj.get("model_weights_location"),
            "progress": obj.get("progress"),
            "model_pr": obj.get("model_pr"),
            "retry_count": obj.get("retry_count"),
            "max_retries": obj.get("max_retries"),
            "error_message": obj.get("error_message"),
            "cost_usd": obj.get("cost_usd"),
            "billed_minutes": obj.get("billed_minutes"),
            "cost_synced_at": obj.get("cost_synced_at"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at")
        })
        return _obj


