# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Union
from overmind.openapi_client.models.provenance_enum import ProvenanceEnum
from typing import Optional, Set
from typing_extensions import Self

class FinetuningEvidence(BaseModel):
    """
    One benchmark behind a grade. ``percentile`` is standing inside that benchmark's own cohort — raw scores are not comparable across benchmarks and are never sent.
    """ # noqa: E501
    benchmark: StrictStr
    skill: StrictStr
    percentile: Union[StrictFloat, StrictInt]
    cohort_n: StrictInt
    source: StrictStr
    url: StrictStr
    provenance: ProvenanceEnum
    __properties: ClassVar[List[str]] = ["benchmark", "skill", "percentile", "cohort_n", "source", "url", "provenance"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FinetuningEvidence from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FinetuningEvidence from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "benchmark": obj.get("benchmark"),
            "skill": obj.get("skill"),
            "percentile": obj.get("percentile"),
            "cohort_n": obj.get("cohort_n"),
            "source": obj.get("source"),
            "url": obj.get("url"),
            "provenance": obj.get("provenance")
        })
        return _obj


