# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from overmind.openapi_client.models.ingestion_source_enum import IngestionSourceEnum
from typing import Optional, Set
from typing_extensions import Self

class Ingestion(BaseModel):
    """
    Ingestion
    """ # noqa: E501
    id: UUID
    project: UUID
    source: IngestionSourceEnum
    status: StrictStr
    plan: Optional[Any]
    scan: Dict[str, Any]
    effective: Dict[str, Any]
    source_stats: Dict[str, Any]
    excluded_rows: Optional[Any]
    progress: Optional[Any]
    row_count: StrictInt
    error: StrictStr
    dataset: Optional[UUID]
    created_at: datetime
    __properties: ClassVar[List[str]] = ["id", "project", "source", "status", "plan", "scan", "effective", "source_stats", "excluded_rows", "progress", "row_count", "error", "dataset", "created_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Ingestion from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "project",
            "source",
            "status",
            "plan",
            "scan",
            "effective",
            "source_stats",
            "excluded_rows",
            "progress",
            "row_count",
            "error",
            "dataset",
            "created_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if plan (nullable) is None
        # and model_fields_set contains the field
        if self.plan is None and "plan" in self.model_fields_set:
            _dict['plan'] = None

        # set to None if excluded_rows (nullable) is None
        # and model_fields_set contains the field
        if self.excluded_rows is None and "excluded_rows" in self.model_fields_set:
            _dict['excluded_rows'] = None

        # set to None if progress (nullable) is None
        # and model_fields_set contains the field
        if self.progress is None and "progress" in self.model_fields_set:
            _dict['progress'] = None

        # set to None if dataset (nullable) is None
        # and model_fields_set contains the field
        if self.dataset is None and "dataset" in self.model_fields_set:
            _dict['dataset'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Ingestion from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "project": obj.get("project"),
            "source": obj.get("source"),
            "status": obj.get("status"),
            "plan": obj.get("plan"),
            "scan": obj.get("scan"),
            "effective": obj.get("effective"),
            "source_stats": obj.get("source_stats"),
            "excluded_rows": obj.get("excluded_rows"),
            "progress": obj.get("progress"),
            "row_count": obj.get("row_count"),
            "error": obj.get("error"),
            "dataset": obj.get("dataset"),
            "created_at": obj.get("created_at")
        })
        return _obj


