# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Kind146Enum(str, Enum):
    """
    * `code_bundle` - Code Bundle * `run_output` - Run Output * `diff` - Diff * `log` - Log
    """

    """
    allowed enum values
    """
    CODE_BUNDLE = 'code_bundle'
    RUN_OUTPUT = 'run_output'
    DIFF = 'diff'
    LOG = 'log'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Kind146Enum from a JSON string"""
        return cls(json.loads(json_str))


