# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class Kind2dbEnum(str, Enum):
    """
    * `upload_bundle` - Upload Bundle * `run_agent` - Run Agent * `apply_patch` - Apply Patch * `reset` - Reset
    """

    """
    allowed enum values
    """
    UPLOAD_BUNDLE = 'upload_bundle'
    RUN_AGENT = 'run_agent'
    APPLY_PATCH = 'apply_patch'
    RESET = 'reset'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of Kind2dbEnum from a JSON string"""
        return cls(json.loads(json_str))


