# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.job_status_enum import JobStatusEnum
from overmind.openapi_client.models.job_type_enum import JobTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class PatchedJobRequest(BaseModel):
    """
    PatchedJobRequest
    """ # noqa: E501
    job_type: Optional[JobTypeEnum] = None
    prompt_slug: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    status: Optional[JobStatusEnum] = None
    celery_task_id: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    result: Optional[Any] = None
    analyzer_model: Optional[Annotated[str, Field(strict=True, max_length=128)]] = None
    num_iterations: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    candidates_per_iteration: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=-2147483648)]] = None
    data_source: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=20)]] = None
    baseline_score: Optional[Union[StrictFloat, StrictInt]] = None
    best_score: Optional[Union[StrictFloat, StrictInt]] = None
    improvement: Optional[Union[StrictFloat, StrictInt]] = None
    report_markdown: Optional[StrictStr] = None
    best_agent_code: Optional[StrictStr] = None
    backtest_results: Optional[Any] = None
    kind: Optional[StrictStr] = None
    payload: Optional[Any] = None
    seq: Optional[Annotated[int, Field(le=9223372036854775807, strict=True, ge=-9223372036854775808)]] = None
    error: Optional[StrictStr] = None
    project: Optional[UUID] = None
    agent: Optional[UUID] = None
    triggered_by: Optional[StrictInt] = None
    parent: Optional[UUID] = None
    client_session: Optional[UUID] = None
    eval_run: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["job_type", "prompt_slug", "status", "celery_task_id", "result", "analyzer_model", "num_iterations", "candidates_per_iteration", "data_source", "baseline_score", "best_score", "improvement", "report_markdown", "best_agent_code", "backtest_results", "kind", "payload", "seq", "error", "project", "agent", "triggered_by", "parent", "client_session", "eval_run"]

    @field_validator('kind')
    def kind_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['upload_bundle', 'run_agent', 'apply_patch', 'reset', '']):
            raise ValueError("must be one of enum values ('upload_bundle', 'run_agent', 'apply_patch', 'reset', '')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if result (nullable) is None
        # and model_fields_set contains the field
        if self.result is None and "result" in self.model_fields_set:
            _dict['result'] = None

        # set to None if baseline_score (nullable) is None
        # and model_fields_set contains the field
        if self.baseline_score is None and "baseline_score" in self.model_fields_set:
            _dict['baseline_score'] = None

        # set to None if best_score (nullable) is None
        # and model_fields_set contains the field
        if self.best_score is None and "best_score" in self.model_fields_set:
            _dict['best_score'] = None

        # set to None if improvement (nullable) is None
        # and model_fields_set contains the field
        if self.improvement is None and "improvement" in self.model_fields_set:
            _dict['improvement'] = None

        # set to None if backtest_results (nullable) is None
        # and model_fields_set contains the field
        if self.backtest_results is None and "backtest_results" in self.model_fields_set:
            _dict['backtest_results'] = None

        # set to None if payload (nullable) is None
        # and model_fields_set contains the field
        if self.payload is None and "payload" in self.model_fields_set:
            _dict['payload'] = None

        # set to None if project (nullable) is None
        # and model_fields_set contains the field
        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        # set to None if agent (nullable) is None
        # and model_fields_set contains the field
        if self.agent is None and "agent" in self.model_fields_set:
            _dict['agent'] = None

        # set to None if triggered_by (nullable) is None
        # and model_fields_set contains the field
        if self.triggered_by is None and "triggered_by" in self.model_fields_set:
            _dict['triggered_by'] = None

        # set to None if parent (nullable) is None
        # and model_fields_set contains the field
        if self.parent is None and "parent" in self.model_fields_set:
            _dict['parent'] = None

        # set to None if client_session (nullable) is None
        # and model_fields_set contains the field
        if self.client_session is None and "client_session" in self.model_fields_set:
            _dict['client_session'] = None

        # set to None if eval_run (nullable) is None
        # and model_fields_set contains the field
        if self.eval_run is None and "eval_run" in self.model_fields_set:
            _dict['eval_run'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_type": obj.get("job_type"),
            "prompt_slug": obj.get("prompt_slug"),
            "status": obj.get("status"),
            "celery_task_id": obj.get("celery_task_id"),
            "result": obj.get("result"),
            "analyzer_model": obj.get("analyzer_model"),
            "num_iterations": obj.get("num_iterations"),
            "candidates_per_iteration": obj.get("candidates_per_iteration"),
            "data_source": obj.get("data_source"),
            "baseline_score": obj.get("baseline_score"),
            "best_score": obj.get("best_score"),
            "improvement": obj.get("improvement"),
            "report_markdown": obj.get("report_markdown"),
            "best_agent_code": obj.get("best_agent_code"),
            "backtest_results": obj.get("backtest_results"),
            "kind": obj.get("kind"),
            "payload": obj.get("payload"),
            "seq": obj.get("seq"),
            "error": obj.get("error"),
            "project": obj.get("project"),
            "agent": obj.get("agent"),
            "triggered_by": obj.get("triggered_by"),
            "parent": obj.get("parent"),
            "client_session": obj.get("client_session"),
            "eval_run": obj.get("eval_run")
        })
        return _obj


