# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.split_method_enum import SplitMethodEnum
from typing import Optional, Set
from typing_extensions import Self

class PatchedFinetuningJobRequest(BaseModel):
    """
    PatchedFinetuningJobRequest
    """ # noqa: E501
    project: Optional[UUID] = None
    capability: Optional[UUID] = None
    dataset: Optional[UUID] = None
    eval_dataset: Optional[UUID] = None
    eval_set: Optional[UUID] = None
    validation_enabled: Optional[StrictBool] = None
    validation_split_ratio: Optional[Union[StrictFloat, StrictInt]] = None
    validation_dataset: Optional[UUID] = None
    split_method: Optional[SplitMethodEnum] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    use_case: Optional[StrictStr] = None
    base_model: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = None
    hyperparameters: Optional[Any] = None
    group_id: Optional[UUID] = None
    model_tier: Optional[StrictStr] = None
    max_retries: Optional[Annotated[int, Field(le=2147483647, strict=True, ge=0)]] = None
    __properties: ClassVar[List[str]] = ["project", "capability", "dataset", "eval_dataset", "eval_set", "validation_enabled", "validation_split_ratio", "validation_dataset", "split_method", "name", "use_case", "base_model", "hyperparameters", "group_id", "model_tier", "max_retries"]

    @field_validator('model_tier')
    def model_tier_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['compact', 'small', 'mid', 'large', '']):
            raise ValueError("must be one of enum values ('compact', 'small', 'mid', 'large', '')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedFinetuningJobRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if capability (nullable) is None
        # and model_fields_set contains the field
        if self.capability is None and "capability" in self.model_fields_set:
            _dict['capability'] = None

        # set to None if eval_dataset (nullable) is None
        # and model_fields_set contains the field
        if self.eval_dataset is None and "eval_dataset" in self.model_fields_set:
            _dict['eval_dataset'] = None

        # set to None if eval_set (nullable) is None
        # and model_fields_set contains the field
        if self.eval_set is None and "eval_set" in self.model_fields_set:
            _dict['eval_set'] = None

        # set to None if validation_dataset (nullable) is None
        # and model_fields_set contains the field
        if self.validation_dataset is None and "validation_dataset" in self.model_fields_set:
            _dict['validation_dataset'] = None

        # set to None if hyperparameters (nullable) is None
        # and model_fields_set contains the field
        if self.hyperparameters is None and "hyperparameters" in self.model_fields_set:
            _dict['hyperparameters'] = None

        # set to None if group_id (nullable) is None
        # and model_fields_set contains the field
        if self.group_id is None and "group_id" in self.model_fields_set:
            _dict['group_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedFinetuningJobRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "project": obj.get("project"),
            "capability": obj.get("capability"),
            "dataset": obj.get("dataset"),
            "eval_dataset": obj.get("eval_dataset"),
            "eval_set": obj.get("eval_set"),
            "validation_enabled": obj.get("validation_enabled"),
            "validation_split_ratio": obj.get("validation_split_ratio"),
            "validation_dataset": obj.get("validation_dataset"),
            "split_method": obj.get("split_method"),
            "name": obj.get("name"),
            "use_case": obj.get("use_case"),
            "base_model": obj.get("base_model"),
            "hyperparameters": obj.get("hyperparameters"),
            "group_id": obj.get("group_id"),
            "model_tier": obj.get("model_tier"),
            "max_retries": obj.get("max_retries")
        })
        return _obj


