# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from uuid import UUID
from overmind.openapi_client.models.evaluator_kind_enum import EvaluatorKindEnum
from overmind.openapi_client.models.evaluator_scope_enum import EvaluatorScopeEnum
from overmind.openapi_client.models.evaluator_surface_enum import EvaluatorSurfaceEnum
from overmind.openapi_client.models.evidence_requirement_enum import EvidenceRequirementEnum
from overmind.openapi_client.models.score_data_type_enum import ScoreDataTypeEnum
from typing import Optional, Set
from typing_extensions import Self

class PatchedEvaluatorRequest(BaseModel):
    """
    PatchedEvaluatorRequest
    """ # noqa: E501
    checklist: Optional[Any] = None
    choices: Optional[Any] = None
    variable_mapping: Optional[Any] = None
    config: Optional[Any] = None
    name: Optional[Annotated[str, Field(min_length=1, strict=True, max_length=255)]] = None
    display_name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    description: Optional[StrictStr] = None
    kind: Optional[EvaluatorKindEnum] = None
    scope: Optional[EvaluatorScopeEnum] = None
    rubric_md: Optional[StrictStr] = None
    judge_model: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    score_type: Optional[ScoreDataTypeEnum] = None
    score_min: Optional[Union[StrictFloat, StrictInt]] = None
    score_max: Optional[Union[StrictFloat, StrictInt]] = None
    pass_threshold: Optional[Union[StrictFloat, StrictInt]] = None
    evidence_requirement: Optional[EvidenceRequirementEnum] = None
    surface: Optional[EvaluatorSurfaceEnum] = None
    applicable_roles: Optional[Any] = None
    spec_data: Optional[Any] = None
    requires_reference: Optional[StrictBool] = None
    is_managed: Optional[StrictBool] = None
    is_archived: Optional[StrictBool] = None
    project: Optional[UUID] = None
    capability: Optional[UUID] = None
    __properties: ClassVar[List[str]] = ["checklist", "choices", "variable_mapping", "config", "name", "display_name", "description", "kind", "scope", "rubric_md", "judge_model", "score_type", "score_min", "score_max", "pass_threshold", "evidence_requirement", "surface", "applicable_roles", "spec_data", "requires_reference", "is_managed", "is_archived", "project", "capability"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PatchedEvaluatorRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if checklist (nullable) is None
        # and model_fields_set contains the field
        if self.checklist is None and "checklist" in self.model_fields_set:
            _dict['checklist'] = None

        # set to None if choices (nullable) is None
        # and model_fields_set contains the field
        if self.choices is None and "choices" in self.model_fields_set:
            _dict['choices'] = None

        # set to None if variable_mapping (nullable) is None
        # and model_fields_set contains the field
        if self.variable_mapping is None and "variable_mapping" in self.model_fields_set:
            _dict['variable_mapping'] = None

        # set to None if config (nullable) is None
        # and model_fields_set contains the field
        if self.config is None and "config" in self.model_fields_set:
            _dict['config'] = None

        # set to None if pass_threshold (nullable) is None
        # and model_fields_set contains the field
        if self.pass_threshold is None and "pass_threshold" in self.model_fields_set:
            _dict['pass_threshold'] = None

        # set to None if applicable_roles (nullable) is None
        # and model_fields_set contains the field
        if self.applicable_roles is None and "applicable_roles" in self.model_fields_set:
            _dict['applicable_roles'] = None

        # set to None if spec_data (nullable) is None
        # and model_fields_set contains the field
        if self.spec_data is None and "spec_data" in self.model_fields_set:
            _dict['spec_data'] = None

        # set to None if project (nullable) is None
        # and model_fields_set contains the field
        if self.project is None and "project" in self.model_fields_set:
            _dict['project'] = None

        # set to None if capability (nullable) is None
        # and model_fields_set contains the field
        if self.capability is None and "capability" in self.model_fields_set:
            _dict['capability'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PatchedEvaluatorRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checklist": obj.get("checklist"),
            "choices": obj.get("choices"),
            "variable_mapping": obj.get("variable_mapping"),
            "config": obj.get("config"),
            "name": obj.get("name"),
            "display_name": obj.get("display_name"),
            "description": obj.get("description"),
            "kind": obj.get("kind"),
            "scope": obj.get("scope"),
            "rubric_md": obj.get("rubric_md"),
            "judge_model": obj.get("judge_model"),
            "score_type": obj.get("score_type"),
            "score_min": obj.get("score_min"),
            "score_max": obj.get("score_max"),
            "pass_threshold": obj.get("pass_threshold"),
            "evidence_requirement": obj.get("evidence_requirement"),
            "surface": obj.get("surface"),
            "applicable_roles": obj.get("applicable_roles"),
            "spec_data": obj.get("spec_data"),
            "requires_reference": obj.get("requires_reference"),
            "is_managed": obj.get("is_managed"),
            "is_archived": obj.get("is_archived"),
            "project": obj.get("project"),
            "capability": obj.get("capability")
        })
        return _obj


