# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class PlaygroundChatRequestRequest(BaseModel):
    """
    PlaygroundChatRequestRequest
    """ # noqa: E501
    messages: List[Dict[str, Any]]
    model_id: Annotated[str, Field(min_length=1, strict=True)]
    temperature: Optional[Union[StrictFloat, StrictInt]] = None
    max_tokens: Optional[StrictInt] = None
    top_p: Optional[Union[StrictFloat, StrictInt]] = None
    frequency_penalty: Optional[Union[StrictFloat, StrictInt]] = None
    presence_penalty: Optional[Union[StrictFloat, StrictInt]] = None
    __properties: ClassVar[List[str]] = ["messages", "model_id", "temperature", "max_tokens", "top_p", "frequency_penalty", "presence_penalty"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PlaygroundChatRequestRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PlaygroundChatRequestRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "messages": obj.get("messages"),
            "model_id": obj.get("model_id"),
            "temperature": obj.get("temperature"),
            "max_tokens": obj.get("max_tokens"),
            "top_p": obj.get("top_p"),
            "frequency_penalty": obj.get("frequency_penalty"),
            "presence_penalty": obj.get("presence_penalty")
        })
        return _obj


