# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class RootSpanList(BaseModel):
    """
    Lightweight ``GET /api/traces/`` row — the trace's root span only.  Mirrors what a Jaeger-style \"list traces\" call returns: identity plus the headline fields a UI needs to render a row.
    """ # noqa: E501
    trace_id: StrictStr
    span_id: StrictStr
    project: UUID
    agent: Optional[UUID]
    job: Optional[UUID]
    iteration: Optional[UUID]
    span_type: StrictStr
    operation: StrictStr
    name: StrictStr
    service_name: StrictStr
    kind: StrictInt
    status_code: StrictInt
    status_message: StrictStr
    start_time_ns: StrictInt
    end_time_ns: StrictInt
    duration_ns: StrictInt
    total_tokens: Optional[StrictInt]
    received_at: datetime
    __properties: ClassVar[List[str]] = ["trace_id", "span_id", "project", "agent", "job", "iteration", "span_type", "operation", "name", "service_name", "kind", "status_code", "status_message", "start_time_ns", "end_time_ns", "duration_ns", "total_tokens", "received_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RootSpanList from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "trace_id",
            "span_id",
            "project",
            "agent",
            "job",
            "iteration",
            "span_type",
            "operation",
            "name",
            "service_name",
            "kind",
            "status_code",
            "status_message",
            "start_time_ns",
            "end_time_ns",
            "duration_ns",
            "total_tokens",
            "received_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if agent (nullable) is None
        # and model_fields_set contains the field
        if self.agent is None and "agent" in self.model_fields_set:
            _dict['agent'] = None

        # set to None if job (nullable) is None
        # and model_fields_set contains the field
        if self.job is None and "job" in self.model_fields_set:
            _dict['job'] = None

        # set to None if iteration (nullable) is None
        # and model_fields_set contains the field
        if self.iteration is None and "iteration" in self.model_fields_set:
            _dict['iteration'] = None

        # set to None if total_tokens (nullable) is None
        # and model_fields_set contains the field
        if self.total_tokens is None and "total_tokens" in self.model_fields_set:
            _dict['total_tokens'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RootSpanList from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "trace_id": obj.get("trace_id"),
            "span_id": obj.get("span_id"),
            "project": obj.get("project"),
            "agent": obj.get("agent"),
            "job": obj.get("job"),
            "iteration": obj.get("iteration"),
            "span_type": obj.get("span_type"),
            "operation": obj.get("operation"),
            "name": obj.get("name"),
            "service_name": obj.get("service_name"),
            "kind": obj.get("kind"),
            "status_code": obj.get("status_code"),
            "status_message": obj.get("status_message"),
            "start_time_ns": obj.get("start_time_ns"),
            "end_time_ns": obj.get("end_time_ns"),
            "duration_ns": obj.get("duration_ns"),
            "total_tokens": obj.get("total_tokens"),
            "received_at": obj.get("received_at")
        })
        return _obj


