# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from overmind.openapi_client.models.plan_enum import PlanEnum
from overmind.openapi_client.models.plan_usage import PlanUsage
from typing import Optional, Set
from typing_extensions import Self

class Subscription(BaseModel):
    """
    Current plan / subscription state for the authenticated user.
    """ # noqa: E501
    plan: PlanEnum
    status: Optional[StrictStr]
    credits_usd: Annotated[str, Field(strict=True)]
    credits_granted_usd: Annotated[str, Field(strict=True)]
    start_date: Optional[datetime]
    end_date: Optional[datetime]
    cancel_at_period_end: StrictBool
    usage: PlanUsage
    __properties: ClassVar[List[str]] = ["plan", "status", "credits_usd", "credits_granted_usd", "start_date", "end_date", "cancel_at_period_end", "usage"]

    @field_validator('credits_usd')
    def credits_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,8}(?:\.\d{0,4})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,8}(?:\.\d{0,4})?$/")
        return value

    @field_validator('credits_granted_usd')
    def credits_granted_usd_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^-?\d{0,8}(?:\.\d{0,4})?$", value):
            raise ValueError(r"must validate the regular expression /^-?\d{0,8}(?:\.\d{0,4})?$/")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Subscription from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # set to None if status (nullable) is None
        # and model_fields_set contains the field
        if self.status is None and "status" in self.model_fields_set:
            _dict['status'] = None

        # set to None if start_date (nullable) is None
        # and model_fields_set contains the field
        if self.start_date is None and "start_date" in self.model_fields_set:
            _dict['start_date'] = None

        # set to None if end_date (nullable) is None
        # and model_fields_set contains the field
        if self.end_date is None and "end_date" in self.model_fields_set:
            _dict['end_date'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Subscription from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "plan": obj.get("plan"),
            "status": obj.get("status"),
            "credits_usd": obj.get("credits_usd"),
            "credits_granted_usd": obj.get("credits_granted_usd"),
            "start_date": obj.get("start_date"),
            "end_date": obj.get("end_date"),
            "cancel_at_period_end": obj.get("cancel_at_period_end"),
            "usage": PlanUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None
        })
        return _obj


