# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TypeEnum(str, Enum):
    """
    * `openui` - openui * `text` - text * `tool_result` - tool_result * `error` - error * `confirm_request` - confirm_request * `config_request` - config_request * `plan_proposal` - plan_proposal * `plan_progress` - plan_progress * `navigate` - navigate * `job_wait` - job_wait * `job_status` - job_status * `chart` - chart * `choices` - choices * `options` - options * `comparison` - comparison * `activity` - activity
    """

    """
    allowed enum values
    """
    OPENUI = 'openui'
    TEXT = 'text'
    TOOL_RESULT = 'tool_result'
    ERROR = 'error'
    CONFIRM_REQUEST = 'confirm_request'
    CONFIG_REQUEST = 'config_request'
    PLAN_PROPOSAL = 'plan_proposal'
    PLAN_PROGRESS = 'plan_progress'
    NAVIGATE = 'navigate'
    JOB_WAIT = 'job_wait'
    JOB_STATUS = 'job_status'
    CHART = 'chart'
    CHOICES = 'choices'
    OPTIONS = 'options'
    COMPARISON = 'comparison'
    ACTIVITY = 'activity'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TypeEnum from a JSON string"""
        return cls(json.loads(json_str))


