# coding: utf-8

"""
    Overbae API

    Backend API for the Overclaw / Overmind platform.

    The version of the OpenAPI document: 2.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from uuid import UUID
from overmind.openapi_client.models.annotator_kind_enum import AnnotatorKindEnum
from overmind.openapi_client.models.target_kind_enum import TargetKindEnum
from overmind.openapi_client.models.verdict_outcome_enum import VerdictOutcomeEnum
from typing import Optional, Set
from typing_extensions import Self

class Verdict(BaseModel):
    """
    One evaluator's judgment of one target — the read path for every score detail surface. ``passed``/``scope``/``grain``/``gate``/``sub_scores`` are lifted out of ``metadata`` so consumers never parse it.
    """ # noqa: E501
    id: UUID
    evaluator: Optional[UUID]
    evaluator_name: StrictStr
    display_name: StrictStr
    target_kind: TargetKindEnum
    target_id: StrictStr
    label: StrictStr
    score: Optional[Union[StrictFloat, StrictInt]]
    passed: Optional[StrictBool]
    outcome: VerdictOutcomeEnum
    explanation: StrictStr
    unmet: Optional[Any]
    scope: StrictStr
    grain: StrictStr
    gate: StrictBool
    sub_scores: List[Any]
    annotator_kind: AnnotatorKindEnum
    identifier: StrictStr
    judge_trace_id: StrictStr
    cost: Optional[Union[StrictFloat, StrictInt]]
    latency_ms: Optional[StrictInt]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["id", "evaluator", "evaluator_name", "display_name", "target_kind", "target_id", "label", "score", "passed", "outcome", "explanation", "unmet", "scope", "grain", "gate", "sub_scores", "annotator_kind", "identifier", "judge_trace_id", "cost", "latency_ms", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Verdict from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "id",
            "evaluator",
            "evaluator_name",
            "display_name",
            "target_kind",
            "target_id",
            "label",
            "score",
            "passed",
            "outcome",
            "explanation",
            "unmet",
            "scope",
            "grain",
            "gate",
            "sub_scores",
            "annotator_kind",
            "identifier",
            "judge_trace_id",
            "cost",
            "latency_ms",
            "created_at",
            "updated_at",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if evaluator (nullable) is None
        # and model_fields_set contains the field
        if self.evaluator is None and "evaluator" in self.model_fields_set:
            _dict['evaluator'] = None

        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if passed (nullable) is None
        # and model_fields_set contains the field
        if self.passed is None and "passed" in self.model_fields_set:
            _dict['passed'] = None

        # set to None if unmet (nullable) is None
        # and model_fields_set contains the field
        if self.unmet is None and "unmet" in self.model_fields_set:
            _dict['unmet'] = None

        # set to None if cost (nullable) is None
        # and model_fields_set contains the field
        if self.cost is None and "cost" in self.model_fields_set:
            _dict['cost'] = None

        # set to None if latency_ms (nullable) is None
        # and model_fields_set contains the field
        if self.latency_ms is None and "latency_ms" in self.model_fields_set:
            _dict['latency_ms'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Verdict from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "evaluator": obj.get("evaluator"),
            "evaluator_name": obj.get("evaluator_name"),
            "display_name": obj.get("display_name"),
            "target_kind": obj.get("target_kind"),
            "target_id": obj.get("target_id"),
            "label": obj.get("label"),
            "score": obj.get("score"),
            "passed": obj.get("passed"),
            "outcome": obj.get("outcome"),
            "explanation": obj.get("explanation"),
            "unmet": obj.get("unmet"),
            "scope": obj.get("scope"),
            "grain": obj.get("grain"),
            "gate": obj.get("gate"),
            "sub_scores": obj.get("sub_scores"),
            "annotator_kind": obj.get("annotator_kind"),
            "identifier": obj.get("identifier") if obj.get("identifier") is not None else '',
            "judge_trace_id": obj.get("judge_trace_id"),
            "cost": obj.get("cost"),
            "latency_ms": obj.get("latency_ms"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


